[project]
name = "lichess-bot-leaderboard"
version = "0.1.0"
description = "A leaderboard for lichess bots"
requires-python = ">=3.11"


# pyright
[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "strict"
include = [
  "src",
  "tests",
]
exclude = [
  "**/__pycache__",
  ".venv",
]
