name: 🦋 Check Dependencies Changed
description: Determine if the dependencies for a particular CI job have changed

inputs:
  # https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
  pathspec:
    description: The pathspec to pass to git diff
    required: true

outputs:
  changed:
    description: Whether or not one of the dependencies has changed
    value: ${{ steps.check-diff.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: ⚖️ Check diff
      id: check-diff
      shell: bash
      run: |
        # Check for changed dependencies

        # Error handling and debuggability
        set -e -u -x -o pipefail

        # Log which files are in the diff
        echo "Changed dependencies:"
        git diff --name-only origin/main...HEAD -- \
          '.github/actions/check-dependencies-changed/action.yaml' \
          '.github/workflows/ci.yaml' \
          ${{ inputs.pathspec }}

        # Populate the output
        if git diff --quiet origin/main...HEAD -- \
          '.github/actions/check-dependencies-changed/action.yaml' \
          '.github/workflows/ci.yaml' \
          ${{ inputs.pathspec }}
        ; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
