name: ♟️ CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

env:
  PYTHON_VERSION: "3.11"

jobs:
  # Determine which jobs need to be run
  determine-which-jobs:
    name: 🔮 determine-which-jobs / 🐧 ubuntu
    runs-on: ubuntu-latest
    outputs:
      check-style-prettier: ${{ steps.check-style-prettier.outputs.changed }}
      check-style-css: ${{ steps.check-style-css.outputs.changed }}
      check-style-jijna: ${{ steps.check-style-jinja.outputs.changed }}
      check-style-markdown: ${{ steps.check-style-markdown.outputs.changed }}
      check-style-python: ${{ steps.check-style-python.outputs.changed }}
      check-style-toml: ${{ steps.check-style-toml.outputs.changed }}
      check-types: ${{ steps.check-types.outputs.changed }}
      run-tests: ${{ steps.check-types.outputs.changed }}
      check-coverage: ${{ steps.run-tests.outputs.changed }}
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Determine which jobs need to be run based on which files have changed
      # formatting (css, json, md, yaml)
      - name: 🧚 Determine check-style-prettier
        id: check-style-prettier
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.css' \
            '**/*.json' \
            '**/*.jsonc' \
            '**/*.md' \
            '**/*.yaml' \
            '.prettierignore' \
            '.prettierrc.json' \
      # linting (css)
      - name: 👨‍🎨 Determine check-style-css
        id: check-style-css
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.css' \
            '.stylelintrc.json' \
      # linting and formatting (jinja)
      - name: 🐱‍👤 Determine check-style-jinja
        id: check-style-jinja
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.jinja' \
            'requirements/style-jijna.txt' \
            'djlint.toml' \
      # linting (markdown)
      - name: 👩‍💼 Determine check-style-markdown
        id: check-style-markdown
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.md' \
            '.markdownlint.jsonc' \
      # linting and formatting (python)
      - name: 🤵 Determine check-style-python
        id: check-style-python
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.py' \
            'requirements/style-python.txt' \
            'ruff.toml' \
      # linting and formatting (toml)
      - name: 👷 Determine check-style-toml
        id: check-style-toml
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.toml' \
      # static type checking
      - name: ⌨️ Determine check-types
        id: check-types
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.py' \
            'requirements/leaderboard.txt' \
            'pyproject.toml' \
      # tests
      - name: 🧪 Determine run-tests
        id: run-tests
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.jinja' \
            '**/*.py' \
            'requirements/leaderboard.txt' \
      # coverage
      - name: 🔬 Determine check-coverage
        id: check-coverage
        uses: ./.github/actions/check-dependencies-changed
        with:
          pathspec: |-
            '**/*.jinja' \
            '**/*.py' \
            'requirements/leaderboard.txt' \
            '.coveragerc' \

  # Check formatting (css, json, md, yaml)
  check-style-prettier:
    name: 🧚 check-style-prettier / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs: determine-which-jobs
    if: needs.determine-which-jobs.outputs.check-style-prettier == 'true'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐸 Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: 📦 Install dependencies (node.js)
        run: |
          npm install -g prettier
      # Format
      - name: 🧹 Check format (prettier)
        run: |
          prettier . --check --log-level debug

  # Check linting (css)
  check-style-css:
    name: 👨‍🎨 check-style-css / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs:
      - determine-which-jobs
      - check-style-prettier
    if: |
      needs.determine-which-jobs.outputs.check-style-css == 'true' &&
      needs.check-style-prettier.result != 'failure'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐸 Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: 📦 Install dependencies (node.js)
        run: |
          npm -g install stylelint stylelint-config-standard
      # Lint
      - name: ✨ Check lint (stylelint)
        run: |
          stylelint **/*.css

  # Check linting and formatting (jinja)
  check-style-jinja:
    name: 🐱‍👤 check-style-jinja / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs: determine-which-jobs
    if: needs.determine-which-jobs.outputs.check-style-jijna == 'true'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🛠️ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      # Format
      - name: 🧹 Check format (djlint)
        run: |
          djlint templates -e jinja --check
      # Lint
      - name: ✨ Check lint (djlint)
        run: |
          djlint templates -e jinja --lint

  # Check linting (markdown)
  check-style-markdown:
    name: 👩‍💼 check-style-markdown / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs:
      - determine-which-jobs
      - check-style-prettier
    if: |
      needs.determine-which-jobs.outputs.check-style-markdown == 'true' &&
      needs.check-style-prettier.result != 'failure'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      # Lint
      - name: ✨ Check lint (markdownlint)
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"

  # Check linting and formatting (python)
  check-style-python:
    name: 🤵 check-style-python / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs: determine-which-jobs
    if: needs.determine-which-jobs.outputs.check-style-python == 'true'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐩 Set up Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: latest
      # Format
      - name: 🧹 Check format (ruff)
        run: |
          ruff format --check
      # Lint
      - name: ✨ Check lint (ruff)
        run: |
          ruff check

  # Check linting and formatting (toml)
  check-style-toml:
    name: 👷 check-style-toml / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs: determine-which-jobs
    if: needs.determine-which-jobs.outputs.check-style-toml == 'true'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🚿 Set up Taplo
        uses: uncenter/setup-taplo@v1
      # Format
      - name: 🧹 Check format (taplo)
        run: |
          taplo fmt --check
      # Lint
      - name: ✨ Check lint (taplo)
        run: |
          taplo check

  # Run static type checking
  check-types:
    name: ⌨️ check-types / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs:
      - determine-which-jobs
      - check-style-python
    if: |
      needs.determine-which-jobs.outputs.check-types == 'true' &&
      needs.check-style-python.result != 'failure'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🛠️ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/leaderboard.txt
      - name: 🐸 Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: 📦 Install dependencies (node.js)
        run: |
          npm install -g pyright
      # Static type checking
      - name: 🗿 Perform static type checking (pyright)
        run: |
          pyright --verbose

  # Run tests on mac, windows, and ubuntu
  run-tests:
    name: 🧪 run-tests / ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs:
      - determine-which-jobs
      - check-style-jinja
      - check-types
    if: |
      needs.determine-which-jobs.outputs.run-tests == 'true' &&
      needs.check-style-jinja.result != 'failure' &&
      needs.check-types.result != 'failure'
    strategy:
      matrix:
        include:
          - { name: 🐧 ubuntu, os: ubuntu-latest }
          - { name: 🖼️ windows, os: windows-latest }
          - { name: 🍏 macos, os: macos-latest }
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🛠️ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/leaderboard.txt
      # Run tests
      - name: ⚗️ Run unit tests
        run: |
          python -m unittest discover -v -s tests -p test_*.py

  # Ensure that the tests did not fail
  # This is done because it doesn't seem to be possible to have both:
  # - a matrix job which is skippable
  # - a branch protection rule requiring that matrix job
  # This is because the name of the jobs depend on whether or not they were skipped
  check-test-result:
    name: 🩺 check-test-result / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs: run-tests
    if: needs.run-tests.result != 'skipped'
    steps:
      - name: 🙄 Check result
        run: |
          if ${{ needs.run-tests.result == 'success' }}; then
            echo "run-tests succeeded!"
          else
            echo "run-tests did not succeeded!"
            exit 1
          fi

  # Run coverage and generate artifacts
  check-coverage:
    name: 🔬 check-coverage / 🐧 ubuntu
    runs-on: ubuntu-latest
    needs:
      - determine-which-jobs
      - run-tests
    if: |
      needs.determine-which-jobs.outputs.check-coverage == 'true' &&
      needs.run-tests.result != 'failure'
    steps:
      # Setup
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🛠️ Install dependencies (python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/all.txt
      # Run tests with coverage
      - name: ☂️ Run unittest with coverage
        run: |
          coverage run
      # Coverage xml
      - name: 📃 Generate coverage xml
        run: |
          coverage xml
        # Comment about code coverage on PRs
      - name: 🐒 Comment coverage on PR
        if: ${{ github.event_name == 'pull_request' }}
        # Use an old version to avoid adding a check to the workflow
        uses: 5monkeys/cobertura-action@v9
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage.xml
          skip_covered: false
          minimum_coverage: 80
          show_line: true
          show_branch: true
          show_missing: true
      # Coverage html
      - name: 📊 Generate coverage html
        run: |
          coverage html
      # Upload coverage artifacts
      - name: 🤳 Upload coverage html
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
